name: Bug Report 🐞
description: Report a bug or issue.
title: "[scope-here] Descriptive-title-here"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        # Thanks for Reporting a Bug! 🐛

        ⚠ Delete `[scope-here]` in the title above if you are not sure.

        Help us replicate the issue by filling in this form. Please read the [contribution guide](https://github.com/latipun7/.github/blob/main/contributing.md#contribution-guide).

        Thank you 🥳

  - type: checkboxes
    attributes:
      label: Assurance
      description: Please read the [contribution guide here](https://github.com/latipun7/.github/blob/main/contributing.md#contribution-guide).
      options:
        - label: I have read and understand the contribution guide, and
          required: true
        - label: I'm sure there's no relevant issue in this repository
          required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Environment
      value: |
        | tool          | version |
        |---------------|---------|
        | `OS`          | Ubuntu  |
        | `node`        | 16.13.0 |
        | `xxxx`        | X.X.X   |
    validations:
      required: false

  - type: textarea
    attributes:
      label: Other Information
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
